### ISSUE TITLE
How to detect re-renders?

### ISSUE THREAD

**Issue by ConsoleTVs** [typescene/typescene#56]
I am wondering how does the project detect re-renders, in the counter example, you increment the prop of the class directly. How do you detect it's time to render again because of that side effect?

PD; Very nice project, no dependencies and great ideas. Looking forward more!

**Comment by jcormont** [comment]
Thanks! Development has been a little slow recently because of work, but great to hear positive feedback. 

Typescene keeps track of bindings (in the example there is a binding in the view), and then, when the target component is constructed, the bound properties are defined with a getter and setter. These update 'bound' binding(s) immediately - in this case a property of the view component.

The view property is observed in the same way, and any change updates the DOM.

**Comment by ConsoleTVs** [comment]
So you use a proxy to modify the class and set a global getter to it? This is cool!
