### ISSUE TITLE
Bootstrap compatibility?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [typescene/typescene#69]
I first came across typescene-ui but noticed that it says "deprecated in favor of scoped package"

Does typescene still support generation of Bootstrap compatible code?

**Comment by jcormont** [comment]
Hi, indeed the old package works differently from the new one. It generated DOM elements that were styled using Bootstrap 3, using its grid system etc. 

The new `typescene-webapp` package uses its own base classes for layout and styling because Bootstrap 4 didn't seem to be going in a direction that would be compatible anymore.

However, you can still override the default classes and styles in an app and basically use Bootstap classes for controls, just not layout.

**Comment by mfreeman-xtivia** [comment]
Oh well.

Thanks for the quick response. I was really excited when i saw the Bootstrap support as this is a must-have for my situation. Will keep on looking for something else.

Again thanks for the response.
